### PR TITLE
Bugfixes downloads

### PR DESCRIPTION
**Pull request by l-vincent-l**
We were not allowed to download a file when the user is not logged in.

### CODE REVIEW

**Comment by l-vincent-l** [comment]
Any news on this one?

**Comment by maukoquiroga** [comment]
Hi guys, would love to have your feedback on this one so we can move forward.

**Comment by abyrd** [comment]
Hi @l-vincent-l and @maukoquiroga. It appears I didn't have notifications enabled on this repo because I wasn't alerted when you commented. I'm fixing that now. 

Currently we are completely focused on replacing MapDB with other data storage backends. We are quite close to finishing this but must continue that work.

Of course this PR is not particularly complex and doesn't directly interefere with that other work, but there's still the same problem as the last time we discussed: this PR does not reference any issue and has no true description of the intended effect of the changes.

We've looked it over a few times and it appears to just grant all permissions to any user on the public interface when not logged in. While we can guess to some degree what you're confronting / trying to achieve here, it's not clear that this fits with any coherent model of user permissions. We would need a serious discussion on an issue of what problem you're encountering and a full coherent account permissions solution. This is already a topic of debate among the rest of us.

**Comment by l-vincent-l** [comment]
Not needed anymore

**Pull request closed without merging**
