### PR TITLE
Add datagouvfr extension

### PR DESCRIPTION
**Pull request by l-vincent-l**
We were not allowed to download a file when the user is not logged in.

### CODE REVIEW

**Comment by landonreed** [comment]
@l-vincent-l, we're going to merge this code and I will adapt it to match the changes in #32 that makes common more of the boilerplate code that was necessarily included in your original PR.  Please see #32 to follow this work.

**Comment by l-vincent-l** [comment]
Done

**Comment by landonreed** [comment]
Sorry, @l-vincent-l, one more thing.  Could you explain the changes to `FeedSource.java` (code comments eventually, but a message here is ok)?

It looks like this is a pretty significant change to how fetch URLs are used and I wouldn't expect an extension to need this kind of change.  Perhaps this could be addressed with some of my changes in #32?

**Comment by l-vincent-l** [comment]
The thing is that I want to fetch url from an API endpoint (e.g. `http://www.data.gouv.fr/api/1/datasets/horaires-des-tram-train-ter-pays-de-la-loire/`)
In this endpoint I want to be able to download the dataset at that URL :  `https://ressources.data.sncf.com/explore/dataset/sncf-tram-train-ter-pdl-gtfs/download?format=csv&timezone=Europe/Berlin&use_labels_for_header=true`
So my URL isn't stored, but retrieved from the API.

**Comment by landonreed** [comment]
If `https://ressources.data.sncf.com/explore/dataset/sncf-tram-train-ter-pdl-gtfs/download?format=csv&timezone=Europe/Berlin&use_labels_for_header=true ` is a static URL, is there any reason that it can't be stored during import rather than fetched each time it is needed?

**Comment by l-vincent-l** [comment]
It might change, so I want to reference the datagouv url.

**Comment by maukoquiroga** [comment]
News?

**Comment by abyrd** [comment]
Hi @maukoquiroga and @l-vincent-l, I've switched on notifications for this repo now. I wasn't keeping up on the comments before. As stated elsewhere we're focused completely on replacing the MapDB backend, which is a large task. Landon had begun refactoring the extension points so we could reuse more code, and this should also make your implementation simpler. But we can't make that a priority until we truly complete this storage backend transition. I'm thinking that should be basically finished next week.

**Comment by maukoquiroga** [comment]
Hi there, as I guess you've finished replacing the MapDB backend, could we have a visibility on this one? Thanks 😄 .

**Comment by l-vincent-l** [comment]
Not needed anymore.

**Pull request closed without merging**
